apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 
    targetRevision: HEAD
    path: argo/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ashwani
  syncPolicy:
    automated:
      prune: false
      selfHeal: false